# Generated by Django 5.2.3 on 2025-06-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
