# Generated by Django 5.2.3 on 2025-06-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='destinations/'),
        ),
    ]
