# Generated by Django 5.2.3 on 2025-06-16 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='destination',
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(upload_to='activity_images/'),
        ),
    ]
