# Generated by Django 5.2.3 on 2025-06-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_destination_activity_created_at_and_more'),
        ('destinations', '0003_alter_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destination'),
            preserve_default=False,
        ),
    ]
